### PR TITLE
Fix/use new sdk

### LINKED ISSUE #25: To take advantage of new SDK optimizations
- Liquidator behind the SDK. Missing triangulation fix, RPC call optimizations, lazy oracle, and auto symbol-refresh on expiry.
- It still has the redundant RPC heavy init across the three services (every start of sentinel, commander, and executor does its own full createProxyInstance())

### PR DESCRIPTION
**Pull request by souhailaS**
This PR Closes #25 
- Introduced a shared SDK state cache in Redis. Commander became the state leader. It does the full init, then publishes snapshots for others.
 - Sentinel bootstraps from the cache, falls back to full init if the cache is missing or unusable.
 - Executor now shares a single MarketData across all bots, replacing per-bot full init. (we run this with 5 bots)
  - Commander now throws a clear fatal on `all RPCs down` instead of logging and crashing later ..
  - Added Controlled exit paths. Every service's entry point catches init failures and exits with a clean fatal log.
  - awaited Sentinel's start (it think the await was forgoten) so rejections actually surface ..

### CODE REVIEW

File: src/executor/liquidator.ts [hunk 1]
```diff
@@ -99,26 +102,14 @@ export default class Liquidator {
...
-    }
-    if (!success) {
-      throw new Error("critical: all RPCs are down");
-    }
+    const md = new MarketData(this.sdkConfig);
+    const result = await initMarketDataWithCache(md, this.providers, this.redisPubClient);
+    // TODO: use a proper logger
+    console.log(
+      `${new Date(Date.now()).toISOString()}: executor MarketData initialized ` +
+        `(cache=${result.usedCache}${formatCacheAgeSuffix(result)}, providerIndex=${result.providerIndex})`
```
Comment (b1674927) [inline src/executor/liquidator.ts:110]: why switching to a fixed provider index?

Comment (souhailaS) [reply src/executor/liquidator.ts:110]: The array is already shuffled before reaching the constructor. I added a comment in there to now forget that. 
And cleaned up a subsequent unnecessary shuffling, its redundant.

Comment (souhailaS) [reply src/executor/liquidator.ts:110]: @b1674927 it this ok?

**Review by b1674927 — APPROVED** [review]
The sdk update trigger is not clear to me
